### ISSUE TITLE
Support a single NE instance per solution on Linux, too (OSOE-430)

### ISSUE THREAD

**Issue by 0liver** [Lombiq/NodeJs-Extensions#17]
The OSOCE build time can be significantly reduced by using a single copy of the Node.js Extensions NPM package instead of one for every project which uses NE. This only applies to the usage via submodule, though.

The idea is to use an MSBuild property to trigger the NPM package installation as part of the Node.js Extensions project build rather than as part of the build of its dependent projects. Since all dependent projects will be built AFTER NE itself, there's no issue with concurrency or locking.

Once NE has its NPM package installed, all dependent module can simply link to that installation (using pnpm) which is a fast and cheap operation.

This will save several tens of seconds per project. Taking into account parallel builds, it should yield a speed-up of 1 to 3 minutes per build. And it does.

### Linux support currently disabled

The above has been implemented in v1.0.0 of the module, but had to be deactivated for **Linux** builds due to the different handling of symlinked directories, which breaks the support for a single NE installation.

This should be fixed.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-430)

**Comment by Piedone** [comment]
Is this still relevant?

**Comment by 0liver** [comment]
Yes, but I'll have to update it. Will do later.

**Comment by Piedone** [comment]
Can you please update this?

**Comment by 0liver** [comment]
Done.

**Comment by Piedone** [comment]
Thanks!

**Comment by Piedone** [comment]
Is this related to the OSOCE Linux builds taking roughly the same time as the Windows ones?

**Comment by 0liver** [comment]
Yes.

**Comment by Piedone** [comment]
Does your work under https://github.com/Lombiq/NodeJs-Extensions/issues/39 overlap with this?

**Comment by 0liver** [comment]
No.

**Comment by 0liver** [comment]
Just to put anyone picking this up on the right track:

The source of this functionality breaking on Linux is the fact that the symlink'ed directories _node_modules\nodejs-extensions_ underneath each project are resolved to the central installation directory of NE, which will be _OSOCE\node_modules\.nx_.

We use directory traversal via `..\..` from the NE directory into its hosting project directory, which works on Windows, because it does **not** resolve the symlink  _project\node_modules\nodejs-extensions_ and **will** end up in _project_, while on Linux it will start traversing from _OSOCE\node_modules\.nx_ and end up in the repo root instead of _project_.

I've already started to fix this issue by adding a custom script, `getCwd`, to NE which works around the symlink resolution on Linux, but it has to be used in all the necessary places in all the scripts, so that the build passes.

I'll leave the PRs open as they are because they already point in the right direction.

**Comment by Piedone** [comment]
This is attempted again under https://github.com/Lombiq/NodeJs-Extensions/pull/78.
