### ISSUE TITLE
Exceeds OS Max Path Limit (OSOE-557)

### ISSUE THREAD

**Issue by thepigeonfighter** [Lombiq/NodeJs-Extensions#23]
Hey there, I was trying to get the Lombiq Training Demo for Orchard Core set up. But in the rebuilding process I got this error. 
~~~
The project 'Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis' ran into a problem during the last operation: Cannot expand metadata in expression 
"$([MSBuild]::ValueOrDefault('%(FullPath)', '').StartsWith($([MSBuild]::EnsureTrailingSlash($(MSBuildProjectDirectory)))))". 
The item metadata "%(FullPath)" cannot be applied to the path "node_modules\nodejs-extensions\node_modules\%40textlint-rule\textlint-rule-no-invalid-control-character\lib\CONTROL_CHARACTERS.js".
 Path: C:\Repo\OrchidDemo\Open-Source-Orchard-Core-Extensions\src\Utilities\Lombiq.NodeJs.Extensions\Lombiq.NodeJs.Extensions.SolutionMarkdownAnalysis\node_modules\nodejs-extensions\node_modules\@textlint-rule\textlint-rule-no-invalid-control-character\lib\CONTROL_CHARACTERS.js exceeds the OS max path limit. 
The fully qualified file name must be less than 260 characters. 
 C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets 
You may need to reload the solution after fixing the problem. 
~~~

From what i understand, I could get around this by moving project directly to my C:\ drive, but that didn't seem right to me especially considering that the project isn't nested that deep in my filesystem currently. So, do I need to move the project up a couple folders or is there a setting I am missing? 

Thanks

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-557)

**Comment by 0liver** [comment]
Thanks for checking out our projects - and thanks for reporting your problem!

Please enable long path support in your windows installation, e.g. following this guide: https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/.

**Comment by thepigeonfighter** [comment]
That fixed it, thanks for the quick response.
