### ISSUE TITLE
Find alternative approach to serialize LinkProjectToNodeJsExtensionsNpmPackage targets execution (OSOE-582)

### ISSUE THREAD

**Issue by dministro** [Lombiq/NodeJs-Extensions#37]
Instead of the current lock file polling, another approach could be more stable and scalable.

Here are some links for inspiration:
 - https://stackoverflow.com/questions/62821122/msbuild-how-to-create-critical-section
 - https://gist.github.com/dedale/675ec80313f2a70266deb0ab78a0e2c6

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-582)

**Comment by 0liver** [comment]
Addressed in https://github.com/Lombiq/NodeJs-Extensions/pull/38.
