### ISSUE TITLE
MSB3073: The command "node scripts/run-pnpm-script "<ProjectName>" build" exited with code -1. (OSOE-593)

### ISSUE THREAD

**Issue by 0liver** [Lombiq/NodeJs-Extensions#39]
Here's an example of the error:

https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4388557195/jobs/7685183926#step:6:114

The cause of the error seems to be a missing script in the _.bin_ folder of the Node.js Extensions NPM package installation, which in case of OSOCE is e.g. _C:\\Projects\\Lombiq\\Osoce\\node_modules\\.nx\\node_modules\\.bin_.

The specific missing script varies. In the above build, `postcss` was missing, but there have been builds where `sass` was missing instead.

### What to do

We need to investigate why `pnpm install` does not create these scripts properly at the given location. And then, we'll have to fix it.

### Ideas

- Add the `--report-summary` switch to all `pnpm run` calls (see https://github.com/pnpm/pnpm/releases/tag/v7.28.0).
- Remove the ` --prefer-offline` flag from the `pnpm install` call in _Lombiq.NodeJs.Extensions\build\NodeJsExtensionsNpmPackage.targets_
- Repeat the `pnpm install` call.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-593)

**Comment by Piedone** [comment]
Is this another random error that breaks the build?

**Comment by 0liver** [comment]
Unfortunately, yes.

**Comment by Piedone** [comment]
Isn't this a bug introduced by https://github.com/Lombiq/Orchard-Training-Demo-Module/issues/108?

**Comment by 0liver** [comment]
Yes. We've fixed a similar bug there, though, and the original one still persists.

**Comment by 0liver** [comment]
The same high-level error has just now appeared in this build: https://github.com/Lombiq/Lombiq-Tenants-Core/actions/runs/4542803172

But the root cause is a different one: pnpm@8 was released last night with some breaking changes.

Let's restrict the version to v7 for now, and in a next step, update to v8.

**Comment by 0liver** [comment]
This was just a drive-by fix for a similar error - reopening.
