### ISSUE TITLE
Add Markdown linting

### ISSUE THREAD

**Issue by Piedone** [Lombiq/NodeJs-Extensions#4]
Just as we have linting for JS and SCSS, let's add linting for Markdown documentation files as well. Follow the example of JS and SCSS linting.

- The first step is to decide what linter to use. We want to check for coding style, as well as spelling/grammar. [markdownlint](https://www.npmjs.com/package/markdownlint) looks like the best candidate for code linting but research the question:
  - It should be available on NPM and actively developed. Similarity in usage to the other linters we use is a plus.
  - See e.g. [this list](https://earthly.dev/blog/markdown-lint/).
  - Check out at least the following tools too: [textlint](https://textlint.github.io/) ([from NPM](https://www.npmjs.com/package/textlint)), [proselint](http://proselint.com/) ([from NPM](https://www.npmjs.com/package/proselint))
  - Maybe we'll need to combine tools.
- Tune rules based on what we have in OSOCE docs files already. Consult the Lombiq team and start polls as necessary.
- Add documentation about using this feature and configuring, as well as suppressing rules, as we have for JS and SCSS linting.
- The API should be as with JS and SCSS linting.
- Should be MSBuild-integrated, as with JS and SCSS linting.
- Is there a way to see linter violations in the IDE like with JS linting (and with SCSS linting in VS Code)? Document it.

**Comment by sarahelsaig** [comment]
Proselint is actually a Python package, The one on NPM is just a wrapper but the main library still must be installed using `pip`. I don't think we want another language framework dependency.

**Comment by Piedone** [comment]
Yep, we don't.

**Comment by Piedone** [comment]
Implemented in https://github.com/Lombiq/NodeJs-Extensions/pull/5.
