### ISSUE TITLE
Upgrade to pnpm@8; drop support for Node.js 14 (OSOE-603)

### ISSUE THREAD

**Issue by 0liver** [Lombiq/NodeJs-Extensions#42]
This should be done once we've upgraded all internal projects and developers to Node.js 16, at least.

There's at least one catch, though. Citing the [v8.0.0 release notes](https://github.com/pnpm/pnpm/releases/tag/v8.0.0):

> A lockfile is generated even for projects with no dependencies.

Also, we should wait a bit until at least a few bug fixes have been incorporated.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-603)

**Comment by Piedone** [comment]
Together with this, the NE reference in `Lombiq.Tests.UI` also needs to be removed, because that's also only there for PNPM 7 compatibility during NuGet publishing.
