### ISSUE TITLE
Add the 'no-constant-binary-expression' rule to .eslintrc.lombiq-base.js (OSOE-721)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/NodeJs-Extensions#84]
See [Interesting bugs caught by no-constant-binary-expression](https://eslint.org/blog/2022/07/interesting-bugs-caught-by-no-constant-binary-expression/).

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-721)

**Comment by Piedone** [comment]
We should have this as all the others as warnings by default (locally you can prototype whatever code you like), and that'll be an error in the CI build.

**Comment by BenedekFarkas** [comment]
Gotcha, updated the description.
