### ISSUE TITLE
Per-project build fails because ".prettierrc.project.js" is not found (OSOE-736)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/NodeJs-Extensions#87]
The error is:
> MSB3030: Could not copy the file "./node_modules/.nx/config/consumer/.prettierrc.project.js" because it was not found.

Attached [logs_191.zip](https://github.com/Lombiq/NodeJs-Extensions/files/13434385/logs_191.zip) contains an example of this happening in a workflow run on a private repo. This is likely caused by OSOE-678.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-736)

**Comment by DemeSzabolcs** [comment]
https://github.com/Lombiq/NodeJs-Extensions/pull/88
